let questions = {
  questions: [
    "Who is most likely to arrive late to a meeting?",
    "Who is most likely to organize office events?",
    "Who is most likely to bring homemade treats to share with the team?",
    "Who is most likely to forget their lunch at home?",
    "Who is most likely to be caught singing at their desk?",
    "Who is most likely to volunteer for overtime?",
    "Who is most likely to win an employee of the month award?",
    "Who is most likely to initiate team-building activities?",
    "Who is most likely to have the messiest desk?",
    "Who is most likely to come up with creative solutions in a crisis?",
    "Who is most likely to be the office prankster?",
    "Who is most likely to take charge during a group project?",
    "Who is most likely to spend the most time in the break room?",
    "Who is most likely to start a fitness challenge in the office?",
    "Who is most likely to bring in motivational quotes for the team?",
    "Who is most likely to be the office fashionista?",
    "Who is most likely to take the longest lunch break?",
    "Who is most likely to forget their computer password?",
    "Who is most likely to organize a surprise birthday party for a colleague?",
    "Who is most likely to win in an office trivia competition?",
    "Who is most likely to binge-watch a TV series during work hours?",
    "Who is most likely to be the go-to person for tech support?",
    "Who is most likely to suggest a new office layout?",
    "Who is most likely to fall asleep during a presentation?",
    "Who is most likely to bring in healthy snacks for the team?",
    "Who is most likely to start a book club at work?",
    "Who is most likely to lead a fitness class during breaks?",
    "Who is most likely to be caught gossiping in the office?",
    "Who is most likely to decorate their desk with personal items?",
    "Who is most likely to be the office DJ for team events?",
    "Who is most likely to take the lead in a client presentation?",
    "Who is most likely to organize team outings?",
    "Who is most likely to have the cleanest desk?",
    "Who is most likely to bring in a pet to the office?",
    "Who is most likely to suggest a new office tradition?",
    "Who is most likely to forget about a scheduled meeting?",
    "Who is most likely to excel in multitasking?",
    "Who is most likely to be the office comedian?",
    "Who is most likely to initiate a mentorship program?",
    "Who is most likely to win the company's annual talent show?",
    "Who is most likely to forget a colleague's name?",
    "Who is most likely to suggest a new office policy?",
    "Who is most likely to be the office mediator during conflicts?",
    "Who is most likely to have the best work-life balance?",
    "Who is most likely to win a costume contest during a themed work event?",
    "Who is most likely to forget where they left their phone?",
    "Who is most likely to bring in snacks for the entire team?",
    "Who is most likely to start a new trend in office fashion?",
    "Who is most likely to be the first to respond to emails?",
    "Who is most likely to participate in a charity run?",
    "Who is most likely to have the most organized inbox?",
    "Who is most likely to bring in a homemade lunch every day?",
    "Who is most likely to lead a team-building retreat?",
    'Who is most likely to win a "Best Dressed" award at a company event?',
    "Who is most likely to organize a team-building escape room experience?",
    "Who is most likely to forget to mute themselves during a virtual meeting?",
    'Who is most likely to be the office "tech guru"?',
    "Who is most likely to suggest a new team-building exercise?",
    "Who is most likely to take on the role of team motivator?",
    "Who is most likely to be the office fashion police?",
    "Who is most likely to bring in a plant to brighten up the office?",
    "Who is most likely to forget their work anniversary?",
    "Who is most likely to start a company podcast?",
    "Who is most likely to organize a themed dress-up day?",
    "Who is most likely to initiate a mentorship program in the company?",
    "Who is most likely to organize a team-building cooking class?",
    "Who is most likely to forget to turn off the office coffee machine?",
    "Who is most likely to be the office trendsetter?",
    "Who is most likely to start a weekly team newsletter?",
    "Who is most likely to bring in a surprise treat for the team?",
    "Who is most likely to mix up important files on their desk?",
    "Who is most likely to organize a team-building improv workshop?",
    "Who is most likely to have a secret talent no one knows about?",
    "Who is most likely to suggest a new office gadget everyone needs?",
    "Who is most likely to forget about a colleague's birthday?",
    "Who is most likely to lead a company-wide volunteer day?",
    "Who is most likely to bring in a homemade dessert for a team celebration?",
    "Who is most likely to organize a team-building board game night?",
    "Who is most likely to forget their headphones at home?",
    'Who is most likely to win the title of "Most Adventurous Employee"?',
    "Who is most likely to suggest a new office policy on remote work?",
    "Who is most likely to bring in a surprise guest speaker for a team meeting?",
    "Who is most likely to suggest a new team-building location?",
    "Who is most likely to have a collection of funny office-themed memes?",
    "Who is most likely to forget about a scheduled training session?",
    "Who is most likely to win the office ping pong tournament?",
    "Who is most likely to initiate a company-wide green initiative?",
    "Who is most likely to forget to submit their timesheet on time?",
    "Who is most likely to suggest a new team-building challenge involving technology?",
    "Who is most likely to be caught talking to themselves at their desk?",
    "Who is most likely to forget their company ID badge?",
    "Who is most likely to bring in a motivational speaker for the team?",
    'Who is most likely to win the title of "Most Tech-Savvy Employee"?',
    "Who is most likely to suggest a new office seating arrangement?",
    "Who is most likely to organize a team-building puzzle-solving day?",
    "Who is most likely to have the best office-themed Zoom background?",
    "Who is most likely to forget to charge their work laptop overnight?",
    "Who is most likely to start a company-wide initiative for eco-friendly practices?",
    "Who is most likely to win the office talent show for the third year in a row?",
    "Who is most likely to bring in a surprise team-building activity for a Monday morning?",
    "Who is most likely to initiate a company-wide initiative for employee well-being?",
    "Who is most likely to forget about a team-building offsite?",
    "Who is most likely to suggest a team-building day at a virtual reality painting class?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
    'Who is most likely to initiate a company-wide "Crazy Sock Day" for laughs?',
    "Who is most likely to propose a team-building day at an indoor rock climbing gym?",
    "Who is most likely to organize a surprise team-building day at a go-kart racing track?",
    "Who is most likely to suggest a team-building day at a virtual reality arcade?",
    "Who is most likely to have a collection of amusing office-themed jigsaw puzzles?",
    "Who is most likely to create a humorous office-themed podcast for team enjoyment?",
    "Who is most likely to have a collection of amusing office-themed comic books?",
    'Who is most likely to initiate a company-wide "Wacky Tie Wednesday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality painting class?",
    "Who is most likely to organize a surprise team-building day at an escape room?",
    "Who is most likely to suggest a team-building day at a board game cafe?",
    "Who is most likely to have a collection of amusing office-themed playing cards?",
    "Who is most likely to create a funny office-themed mobile game for team breaks?",
    'Who is most likely to initiate a company-wide "Mismatched Clothes Monday" tradition?',
    "Who is most likely to propose a team-building day at a laser tag arena?",
    "Who is most likely to have a collection of amusing office-themed action figures?",
    "Who is most likely to start a tradition of sending funny e-cards for work achievements?",
    "Who is most likely to create a humorous office-themed board game for team bonding?",
    "Who is most likely to have a collection of amusing office-themed magnets on their desk?",
    'Who is most likely to initiate a company-wide "Funky Hat Friday" tradition?',
    "Who is most likely to propose a team-building day at a virtual reality escape room?",
    "Who is most likely to have a collection of amusing office-themed bumper stickers?",
    "Who is most likely to organize a surprise team-building day at an indoor trampoline park?",
    "Who is most likely to suggest a team-building day at a chocolate-making workshop?",
    "Who is most likely to create a funny office-themed rap song for team morale?",
    "Who is most likely to have a collection of amusing office-themed coloring books?",
  ],
  nsfw_prompts: [
    "Who is most likely to hook up with someone at a party?",
    "Who is most likely to send a flirty text to the wrong person?",
    "Who is most likely to streak or flash at a festival?",
    "Who is most likely to have an embarrassing sexting history?",
    "Who is most likely to get caught doing something kinky?",
    "Who is most likely to try out a wild dating app?",
    "Who is most likely to kiss someone just to win a dare?",
    "Who is most likely to have a secret crush on someone in the group?",
    "Who is most likely to send unsolicited nudes?",
    "Who is most likely to hook up with an ex again?",
    "Who is most likely to have a one-night stand while traveling?",
    "Who is most likely to make out in a public place?",
    "Who is most likely to lie about their number of hookups?",
    "Who is most likely to flirt with a stranger for fun?",
    "Who is most likely to play strip poker or other risqué games?",
    "Who is most likely to have a sexy hidden talent?",
    "Who is most likely to send a naughty meme or gif to the group chat?",
    "Who is most likely to sneak into someone’s bed just for cuddles?",
    "Who is most likely to try something adventurous in the bedroom?",
    "Who is most likely to get caught watching something they shouldn’t?",
    "Who is most likely to have a foot fetish?",
    "Who is most likely to be caught having sex?",
    "Who is most likely to have a weird sex dream about someone?",
    "Who is most likely to participate in an orgy?",
    "Who is most likely to have a threesome with their partner?",
    "Who is most likely to fantasise about someone?",
    "Who is most likely to watch someone having sex in real life?",
    "Who is most likely to pee themselves in bed?",
    "Who is most likely to have a nightfall regularly?",
    "Who is most likely to accidentally share a nude with the wrong audience?",
    "Who is most likely to call someone daddy/mommy in bed?",
    "Who is most likely to sext while drunk?",
    "Who is most likely to get handsy in public?",
    "Who is most likely to give a lap dance?",
    "Who is most likely to use toys during solo time?",
    "Who is most likely to roleplay in the bedroom?",
    "Who is most likely to have a secret kink?",
    "Who is most likely to send a risqué selfie first?",
    "Who is most likely to flirt with multiple people at once?",
    "Who is most likely to start a steamy group chat?",
    "Who is most likely to get caught watching porn at an awkward time?",
    "Who is most likely to fake it during sex?",
    "Who is most likely to moan too loudly?",
    "Who is most likely to propose a naughty dare at a party?",
    "Who is most likely to fantasise about a friend’s partner?",
    "Who is most likely to experiment with BDSM?",
    "Who is most likely to get caught in a compromising position by a friend?",
    "Who is most likely to send someone a “good morning nude”?",
    "Who is most likely to have a favorite position they brag about?",
    "Who is most likely to flirt with the bartender at a party?",
    "Who is most likely to get handcuffed for fun?",
    "Who is most likely to have a naughty nickname for a friend?",
    "Who is most likely to make out with someone on a dare?",
    "Who is most likely to kiss someone in a pool?",
    "Who is most likely to have a sex playlist ready?",
    "Who is most likely to watch an adult movie with friends for laughs?",
    "Who is most likely to sneakily touch someone in public?",
    "Who is most likely to flirt with someone just for attention?",
    "Who is most likely to get caught flirting in class or work?",
    "Who is most likely to make a “sexy bet” during a game night?",
    "Who is most likely to send a naughty snap to the wrong person?",
    "Who is most likely to sleep with someone on the first date?",
    "Who is most likely to kiss someone under the mistletoe?",
    "Who is most likely to have a hidden crush on a celebrity?",
    "Who is most likely to get handsy while drunk?",
    "Who is most likely to propose a sexy challenge?",
    "Who is most likely to have a secret booty call?",
    "Who is most likely to get caught making out somewhere public?",
    "Who is most likely to flirt using only emojis?",
    "Who is most likely to send a seductive text first?",
    "Who is most likely to have a secret crush on someone’s partner?",
    "Who is most likely to play truth or dare and escalate it?",
    "Who is most likely to kiss more than one person at a party?",
    "Who is most likely to sext someone in the middle of the night?",
    "Who is most likely to make a risky bet for a kiss?",
    "Who is most likely to have a sexual bucket list?",
    "Who is most likely to get caught skinny dipping?",
    "Who is most likely to get naughty in a public place?",
    "Who is most likely to send an NSFW photo as a joke?",
    "Who is most likely to roleplay as a character during sex?",
    "Who is most likely to kiss someone in the rain?",
    "Who is most likely to hook up with someone on vacation?",
    "Who is most likely to have a secret fetish?",
    "Who is most likely to send a flirty voice note?",
    "Who is most likely to experiment with spanking?",
    "Who is most likely to flirt with their crush openly?",
    "Who is most likely to fake being single to flirt?",
    "Who is most likely to try kissing a friend on a dare?",
    "Who is most likely to get caught making a sexy video?",
    "Who is most likely to send a naughty snap with a filter?",
    "Who is most likely to flirt with someone over text for hours?",
    "Who is most likely to sneak a hand in someone’s pocket?",
    "Who is most likely to kiss someone during a dare game?",
    "Who is most likely to have a hidden sexy talent?",
    "Who is most likely to fantasise about a friend during a party?",
    "Who is most likely to get caught watching something explicit at the wrong time?",
    "Who is most likely to send a “hot” selfie without context?",
    "Who is most likely to suggest a sexy drinking game?",
    "Who is most likely to kiss multiple people in one night?",
    "Who is most likely to start a steamy rumor for fun?",
    "Who is most likely to pee themselves in bed?",
    "Who is most likely to have a nightfall regularly?",
    "Who is most likely to accidentally share a nude?",
    "Who is most likely to have a weird sex toy?",
    "Who is most likely to electrocuted by their sex toy?",
    "Who is most likely to have a secret partner/hookup?",
    "Who is most likely to get caught masturbating?",
    "Who is most likely to have a crush on their teacher/professor/boss?",
    "Who is most likely to have a wardrobe malfunction in public?",
    "Who is most likely to get a lap dance?",
    "Who is most likely to have a sexy Halloween costume?",
    "Who is most likely to make a sex tape?",
    "Who is most likely to go skinny dipping?",
    "Who is most likely to have a secret fetish?",
    "Who is most likely to crack an inappropriate joke?",
    "Who is most likely to ?",
  ],
  general_prompts: [
    "Who is most likely to bring snacks to a party?",
    "Who is most likely to laugh at their own jokes?",
    "Who is most likely to lock themselves out of their own house?",
    "Who is most likely to fall asleep in a movie theater?",
    "Who is most likely to binge-watch a whole series in one day?",
    "Who is most likely to get lost while driving?",
    "Who is most likely to make a prank call?",
    "Who is most likely to start a dance-off?",
    "Who is most likely to eat dessert before dinner?",
    "Who is most likely to trip over nothing?",
    "Who is most likely to adopt a pet first?",
    "Who is most likely to win a karaoke contest?",
    "Who is most likely to forget someone’s birthday?",
    "Who is most likely to take a selfie in a funny pose?",
    "Who is most likely to laugh at a serious situation?",
    "Who is most likely to organize a game night?",
    "Who is most likely to lose their phone?",
    "Who is most likely to stay up all night playing video games?",
    "Who is most likely to get scared during a scary movie?",
    "Who is most likely to start a food fight?",
    "Who is most likely to tell a bad joke on purpose?",
    "Who is most likely to oversleep on a weekend?",
    "Who is most likely to win a board game?",
    "Who is most likely to wear mismatched socks?",
    "Who is most likely to forget where they parked?",
    "Who is most likely to break something accidentally?",
    "Who is most likely to get caught singing in public?",
    "Who is most likely to cry while watching a movie?",
    "Who is most likely to prank their friends?",
    "Who is most likely to start a sing-along in public?",
    "Who is most likely to be late to an event?",
    "Who is most likely to embarass themselves in public?",
    "Who is most likely to make a funny face in photos?",
    "Who is most likely to start a group chat?",
    "Who is most likely to tell an embarrassing story?",
    "Who is most likely to laugh until they cry?",
    "Who is most likely to have a random fact ready?",
    "Who is most likely to lose their wallet?",
    "Who is most likely to forget someone’s name?",
    "Who is most likely to order dessert for the table?",
    "Who is most likely to talk to strangers easily?",
    "Who is most likely to sleep through an alarm?",
    "Who is most likely to get sunburned?",
    "Who is most likely to dress up for no reason?",
    "Who is most likely to forget to text back?",
    "Who is most likely to bring a weird gift?",
    "Who is most likely to start a hobby suddenly?",
    "Who is most likely to trip on stairs?",
    "Who is most likely to get caught daydreaming?",
    "Who is most likely to sing in the shower?",
    "Who is most likely to talk in their sleep?",
    "Who is most likely to make a weird noise randomly?",
    "Who is most likely to give a creative nickname?",
    "Who is most likely to laugh at their own mistakes?",
    "Who is most likely to start a new trend?",
    "Who is most likely to get excited over small things?",
    "Who is most likely to make a meme about themselves?",
    "Who is most likely to forget what they were saying mid-sentence?",
    "Who is most likely to organize a fun outing?",
    "Who is most likely to get lost in a new city?",
    "Who is most likely to sleep through a class or meeting?",
    "Who is most likely to make up a story on the spot?",
    "Who is most likely to sing loudly in the car?",
    "Who is most likely to take the longest to get ready?",
    "Who is most likely to lose track of time?",
    "Who is most likely to start a pillow fight?",
    "Who is most likely to take a nap anywhere?",
    "Who is most likely to get excited about snacks?",
    "Who is most likely to tell a corny joke?",
    "Who is most likely to start laughing for no reason?",
    "Who is most likely to forget an important date?",
    "Who is most likely to take a group selfie?",
    "Who is most likely to adopt a random pet?",
    "Who is most likely to dance in public?",
    "Who is most likely to spill coffee on themselves?",
    "Who is most likely to sing the wrong lyrics confidently?",
    "Who is most likely to prank call their friends?",
    "Who is most likely to start a funny debate?",
    "Who is most likely to be the life of the party?",
    "Who is most likely to get scared easily?",
    "Who is most likely to get excited about a random fact?",
    "Who is most likely to give the best advice?",
    "Who is most likely to be first on the dance floor?",
    "Who is most likely to start a silly trend?",
    "Who is most likely to laugh at their own joke twice?",
    "Who is most likely to forget where they put something?",
    "Who is most likely to make a funny video?",
    "Who is most likely to organize a group activity?",
    "Who is most likely to make everyone laugh at dinner?",
    "Who is most likely to spill food accidentally?",
    "Who is most likely to break into song randomly?",
    "Who is most likely to give a creative gift?",
    "Who is most likely to make up a funny nickname?",
    "Who is most likely to make a game out of everything?",
    "Who is most likely to get overly excited about small things?",
    "Who is most likely to laugh at a silly video?",
    "Who is most likely to start a mini-adventure?",
    "Who is most likely to draw something weird?",
    "Who is most likely to win a random contest?",
    "Who is most likely to do something totally unexpected?",
    "Who is most likely to use a disabled toilet in public?",
    "Who is most likely to trip over their own feet?",
    "Who is most likely to get caught talking to themselves?",
    "Who is most likely to get lost in their hometown?",
    "Who is most likely to get an embarassing tatto?",
    "Who is most likely to live the longest?",
    "Who is most likely to appear on a reality TV show?",
  ],
};

module.exports = {
  questions,
};
